In [1]:
import os
import pandas as pd
import numpy as np
import re

In [2]:
top_dir = '/project/'
data_dir = os.path.join(top_dir, 'data')
raw_data_dir = os.path.join(data_dir, 'raw')
os.listdir(raw_data_dir)

['supp_table1.xlsx', 'supp_table4.xlsx']

In [3]:
supp_table1 = pd.read_excel(os.path.join(raw_data_dir, 'supp_table1.xlsx'),
                           engine = 'openpyxl',
                           header = 1)
supp_table4 = pd.read_excel(os.path.join(raw_data_dir, 'supp_table4.xlsx'),
                           engine = 'openpyxl',
                           header = 1)

In [12]:
supp_table1

,Author (Year),Publication Title,Journal,Study Accession,Sample Accession,Sequencing Platform,Library Layout,Subject Health Status,Phenotypea,Age (Years),...,Fasting Blood Glucose (mmol/L),Triglycerides (mmol/L),LDL Cholesterol (mmol/L),Cholesterol (mmol/L),HDL Cholesterol (mmol/L),Physical Exercise (Yes/No/Hours),Smoker (Yes/No),Dairy Product Consumption,Meat Consumption (Yes/No/Vegetarian),Alcohol Consumption (Yes/No/Frequency)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Age (Years),...,Fasting Blood Glucose (mmol/L),Triglycerides (mmol/L),LDL Cholesterol (mmol/L),Cholesterol (mmol/L),HDL Cholesterol (mmol/L),Physical Exercise (Yes/No/Hours),Smoker (Yes/No),Dairy Product Consumption,Meat Consumption (Yes/No/Vegetarian),Alcohol Consumption (Yes/No/Frequency)
1,Jie (2017),The gut microbiome in atherosclerotic cardiova...,Nature Communications,PRJEB21528,SAMEA104142287,Illumina HiSeq 2000,PAIRED,Non-healthy,ACVD,42.8274,...,4.5,1.41,5.24,7.25,0.55,NaN,NaN,NaN,NaN,NaN
2,Jie (2017),The gut microbiome in atherosclerotic cardiova...,Nature Communications,PRJEB21528,SAMEA104142288,Illumina HiSeq 2000,PAIRED,Non-healthy,ACVD,76.0274,...,7.53,1.14,1.54,2.53,0.58,NaN,NaN,NaN,NaN,NaN
3,Jie (2017),The gut microbiome in atherosclerotic cardiova...,Nature Communications,PRJEB21528,SAMEA104142293,Illumina HiSeq 2000,PAIRED,Non-healthy,ACVD,73,...,7.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jie (2017),The gut microbiome in atherosclerotic cardiova...,Nature Communications,PRJEB21528,SAMEA104142291,Illumina HiSeq 2000,PAIRED,Non-healthy,ACVD,45.3973,...,14.56,2.85,1.19,2.68,0.63,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4344,He (2017),Two distinct metacommunities characterize the ...,Gigascience,PRJEB15371,SAMEA4431949,Illumina Hiseq 2000,PAIRED,Non-healthy,Underweight,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4345,He (2017),Two distinct metacommunities characterize the ...,Gigascience,PRJEB15371,SAMEA4431951,Illumina Hiseq 2000,PAIRED,Non-healthy,Underweight,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4346,He (2017),Two distinct metacommunities characterize the ...,Gigascience,PRJEB15371,SAMEA4431964,Illumina Hiseq 2000,PAIRED,Non-healthy,Underweight,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4347,He (2017),Two distinct metacommunities characterize the ...,Gigascience,PRJEB15371,SAMEA4431982,Illumina Hiseq 2000,PAIRED,Non-healthy,Underweight,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4348,aACVD: Atherosclerotic Cardiovascular Disease....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
supp_table4

,Author (Year),Publication Title,Journal,Study Accession,Sample Accession,Sequencing Platform,Library Layout,Subject Health Status,Phenotype,Subject Meta-dataa,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Age (Years),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Vaughn (2016),Increased Intestinal Microbial Diversity follo...,Inflammatory Bowel Disease,PRJNA321058,SAMN05065727,Illumina HiSeq 2500,PAIRED,Non-healthy,Crohn's disease,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Vaughn (2016),Increased Intestinal Microbial Diversity follo...,Inflammatory Bowel Disease,PRJNA321058,SAMN05065737,Illumina HiSeq 2500,PAIRED,Non-healthy,Crohn's disease,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Vaughn (2016),Increased Intestinal Microbial Diversity follo...,Inflammatory Bowel Disease,PRJNA321058,SAMN05065739,Illumina HiSeq 2500,PAIRED,Non-healthy,Crohn's disease,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Vaughn (2016),Increased Intestinal Microbial Diversity follo...,Inflammatory Bowel Disease,PRJNA321058,SAMN05065729,Illumina HiSeq 2500,PAIRED,Non-healthy,Crohn's disease,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
supp_table1_clean = supp_table1.iloc[1:4348, :]
supp_table1_clean.keys()

Index(['Author (Year)', 'Publication Title', 'Journal', 'Study Accession',
       'Sample Accession', 'Sequencing Platform', 'Library Layout',
       'Subject Health Status', 'Phenotypea', 'Subject Meta-datab',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21'],
      dtype='object')

In [6]:
cols_replace_table1 = np.logical_not(supp_table1.iloc[0,:].to_numpy().astype('str') == 'nan')
names_replace_table1 = supp_table1.iloc[0,:][cols_replace_table1]
table1_keynames = supp_table1_clean.keys().to_numpy()
table1_keynames[cols_replace_table1] = names_replace_table1
supp_table1_clean.columsn = table1_keynames
supp_table1_clean

/root/anaconda/envs/microbiome/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """

,Author (Year),Publication Title,Journal,Study Accession,Sample Accession,Sequencing Platform,Library Layout,Subject Health Status,Phenotypea,Age (Years),...,Fasting Blood Glucose (mmol/L),Triglycerides (mmol/L),LDL Cholesterol (mmol/L),Cholesterol (mmol/L),HDL Cholesterol (mmol/L),Physical Exercise (Yes/No/Hours),Smoker (Yes/No),Dairy Product Consumption,Meat Consumption (Yes/No/Vegetarian),Alcohol Consumption (Yes/No/Frequency)
1,Jie (2017),The gut microbiome in atherosclerotic cardiova...,Nature Communications,PRJEB21528,SAMEA104142287,Illumina HiSeq 2000,PAIRED,Non-healthy,ACVD,42.8274,...,4.5,1.41,5.24,7.25,0.55,NaN,NaN,NaN,NaN,NaN
2,Jie (2017),The gut microbiome in atherosclerotic cardiova...,Nature Communications,PRJEB21528,SAMEA104142288,Illumina HiSeq 2000,PAIRED,Non-healthy,ACVD,76.0274,...,7.53,1.14,1.54,2.53,0.58,NaN,NaN,NaN,NaN,NaN
3,Jie (2017),The gut microbiome in atherosclerotic cardiova...,Nature Communications,PRJEB21528,SAMEA104142293,Illumina HiSeq 2000,PAIRED,Non-healthy,ACVD,73,...,7.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jie (2017),The gut microbiome in atherosclerotic cardiova...,Nature Communications,PRJEB21528,SAMEA104142291,Illumina HiSeq 2000,PAIRED,Non-healthy,ACVD,45.3973,...,14.56,2.85,1.19,2.68,0.63,NaN,NaN,NaN,NaN,NaN
5,Jie (2017),The gut microbiome in atherosclerotic cardiova...,Nature Communications,PRJEB21528,SAMEA104142284,Illumina HiSeq 2000,PAIRED,Non-healthy,ACVD,64.589,...,4.61,1.75,4.8,7.47,1.31,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4343,He (2017),Two distinct metacommunities characterize the ...,Gigascience,PRJEB15371,SAMEA4431948,Illumina Hiseq 2000,PAIRED,Non-healthy,Underweight,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4344,He (2017),Two distinct metacommunities characterize the ...,Gigascience,PRJEB15371,SAMEA4431949,Illumina Hiseq 2000,PAIRED,Non-healthy,Underweight,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4345,He (2017),Two distinct metacommunities characterize the ...,Gigascience,PRJEB15371,SAMEA4431951,Illumina Hiseq 2000,PAIRED,Non-healthy,Underweight,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4346,He (2017),Two distinct metacommunities characterize the ...,Gigascience,PRJEB15371,SAMEA4431964,Illumina Hiseq 2000,PAIRED,Non-healthy,Underweight,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4347,He (2017),Two distinct metacommunities characterize the ...,Gigascience,PRJEB15371,SAMEA4431982,Illumina Hiseq 2000,PAIRED,Non-healthy,Underweight,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
supp_table1_clean.columns

Index(['Author (Year)', 'Publication Title', 'Journal', 'Study Accession',
       'Sample Accession', 'Sequencing Platform', 'Library Layout',
       'Subject Health Status', 'Phenotypea', 'Age (Years)', 'Sex',
       'BMI (kg/m²)', 'Fasting Blood Glucose (mmol/L)',
       'Triglycerides (mmol/L)', 'LDL Cholesterol (mmol/L)',
       'Cholesterol (mmol/L)', 'HDL Cholesterol (mmol/L)',
       'Physical Exercise (Yes/No/Hours)', 'Smoker (Yes/No)',
       'Dairy Product Consumption', 'Meat Consumption (Yes/No/Vegetarian)',
       'Alcohol Consumption (Yes/No/Frequency)'],
      dtype='object')

In [8]:
supp_table1_clean.columns

Index(['Author (Year)', 'Publication Title', 'Journal', 'Study Accession',
       'Sample Accession', 'Sequencing Platform', 'Library Layout',
       'Subject Health Status', 'Phenotypea', 'Age (Years)', 'Sex',
       'BMI (kg/m²)', 'Fasting Blood Glucose (mmol/L)',
       'Triglycerides (mmol/L)', 'LDL Cholesterol (mmol/L)',
       'Cholesterol (mmol/L)', 'HDL Cholesterol (mmol/L)',
       'Physical Exercise (Yes/No/Hours)', 'Smoker (Yes/No)',
       'Dairy Product Consumption', 'Meat Consumption (Yes/No/Vegetarian)',
       'Alcohol Consumption (Yes/No/Frequency)'],
      dtype='object')

In [9]:
supp_table4_clean = supp_table4.iloc[2:680, :13]
supp_table4_clean.keys()

Index(['Author (Year)', 'Publication Title', 'Journal', 'Study Accession',
       'Sample Accession', 'Sequencing Platform', 'Library Layout',
       'Subject Health Status', 'Phenotype', 'Subject Meta-dataa',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12'],
      dtype='object')

In [10]:
supp_table4_clean

,Author (Year),Publication Title,Journal,Study Accession,Sample Accession,Sequencing Platform,Library Layout,Subject Health Status,Phenotype,Subject Meta-dataa,Unnamed: 10,Unnamed: 11,Unnamed: 12
2,Vaughn (2016),Increased Intestinal Microbial Diversity follo...,Inflammatory Bowel Disease,PRJNA321058,SAMN05065737,Illumina HiSeq 2500,PAIRED,Non-healthy,Crohn's disease,NaN,NaN,NaN,NaN
3,Vaughn (2016),Increased Intestinal Microbial Diversity follo...,Inflammatory Bowel Disease,PRJNA321058,SAMN05065739,Illumina HiSeq 2500,PAIRED,Non-healthy,Crohn's disease,NaN,NaN,NaN,NaN
4,Vaughn (2016),Increased Intestinal Microbial Diversity follo...,Inflammatory Bowel Disease,PRJNA321058,SAMN05065729,Illumina HiSeq 2500,PAIRED,Non-healthy,Crohn's disease,NaN,NaN,NaN,NaN
5,Vaughn (2016),Increased Intestinal Microbial Diversity follo...,Inflammatory Bowel Disease,PRJNA321058,SAMN05065750,Illumina HiSeq 2500,PAIRED,Non-healthy,Crohn's disease,NaN,NaN,NaN,NaN
6,Vaughn (2016),Increased Intestinal Microbial Diversity follo...,Inflammatory Bowel Disease,PRJNA321058,SAMN05065754,Illumina HiSeq 2500,PAIRED,Non-healthy,Crohn's disease,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
675,Current study,Current study,Current study,NaN,RHB_RAM_0163,Illumina HiSeq 3000/4044,PAIRED,Non-healthy,Rheumatoid arthritis,64,Female,NaN,USA
676,Current study,Current study,Current study,NaN,RHB_RAM_0169,Illumina HiSeq 3000/4045,PAIRED,Non-healthy,Rheumatoid arthritis,59,Female,NaN,USA
677,Current study,Current study,Current study,NaN,RHB_RAM_0182,Illumina HiSeq 3000/4046,PAIRED,Non-healthy,Rheumatoid arthritis,62,Male,NaN,USA
678,Current study,Current study,Current study,NaN,RHB_RAM_0198,Illumina HiSeq 3000/4047,PAIRED,Non-healthy,Rheumatoid arthritis,80,Female,NaN,USA
679,Current study,Current study,Current study,NaN,RHB_RAM_0216,Illumina HiSeq 3000/4048,PAIRED,Non-healthy,Rheumatoid arthritis,74,Male,NaN,USA

In [11]:
preproc_data_dir = os.path.join(data_dir, 'preprocessed')
output_dir = os.path.join(preproc_data_dir, 'preproc_tables')
if not os.path.exists(output_dir):
    os.mkdir(output_dir)
    
supp_table1_clean.to_csv(os.path.join(output_dir, 'supp_table1_clean.csv'))
supp_table4_clean.to_csv(os.path.join(output_dir, 'supp_table4_clean.csv'))